- hosts: "all"
  become: true

- name: Copy a test file
  hosts: "all"
  tasks:
  - name: copy a test file
    copy:
      src: /root/awx/awx/playbooks/hs/hosts /root/awx/awx/playbooks/hs/resolv.conf
      dest: /etc/
      owner: root
      group: root
      mode: '0644'
